# -*- coding: utf-8 -*-
"""FIRST ASSIGNMENT MODDULE 3.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n6uflaumjJUatAOGiAmIzsN5xanyzEQx
"""

'''
1. Explain keyfeatures of python that make it a popular choice for programming ?

 Python is a programming language, use to give instructions to computer to follow and perform the task.
 Key features of python making it  popular choice among programmers are :

 1 - Pythons codes are like english sentences and easily readable .
 2 - Python has large number of libraries used for creating websites, manuplating data, image processing, web devolopment etc
 3 - It has huge number of active number of communtiy support around the world
 4 - portable language easily used many type of operating system
 5 - Python has predefined keywords , straigt forward syntax, reusable syntax like we dont hahave to define that assigned variable is an integer or a string.
 6 - Python has quick run testing which runs code line by line and give outputs .
 '''

'''
2. Describe the role of predefined keywords in python and provide examples of how they are used in a programm ?

Ans . Predefined keywords are special and reserved keywords in python which holds a special meaning with specific purpose in a program whose values are never changed like variables .
     keywords are very important because it control the flow of the program , handling errors , defining functions and class etc.
      some of kewords are and their uses are :
      if-else= conditional statement, break,control = to control the flow of loop , while = to run the the program if the statement is correct, for = creating a loop and iterate over a sequences .
      def= used to define a function , class = used to define a class , try,except,finally= used for error handling, import= used for including external modules .
      '''
      #EXAMPLE


n = int(input("enter a number"))
if n%2 == 0:
    print("number is even")
else:
    print("number is odd")

'''
3. Compare and contrast mutable and immutable objects in python with examples ?

ans. Mutability in programming refers to wheteher the value of an object\container can be changed after they are created is known as
mutable object in python .
examples of mutable objects : list, dictonaries, sets
'''
list = [1,2,3,4]
list[0]            #accesing the first element
list[0] = "aakash" #modifying the first element
list
list[2] = "pwskills"  #adding new element to list at 2 index
list.append("pwskills")
list

'''
Immutable objects are those object's or contanier whose values are not changed after they are created.
the value of object are not modified,add, deletc
Examples of immutable object are : string, tuples, etc.
'''
b = "aakash"
b[0] = p
b

# Commented out IPython magic to ensure Python compatibility.
from collections.abc import ValuesView
'''
4. Discuss different types of operators in python and provide examples of their usage ?

ans. Operators in python are special keywords and symbols that are used to perform operations on variables and values
for manipulation\manage\computation of datas.
ex : a=2, b=3
a+b= 5
+ = operator
There are many type of operator in python such as :
1.ARTHIMATIC OPERATORS are used for performing mathematical calculation.
'''
#examples
a = 2
b = 3
sum = a+b
print(sum)
'''
addition : add two values
substraction : substract ane value from another
multipilication : multiply two Values
division : divide one value with another
# % : returns the reminder
* : use for squaring the or calculatng the power ValueError
\\ : used for floor division
'''
#example
a = 10
b = 3
c = a//b
c = a % b
c = a**b
print(c)

'''
2. COMPARISON OPERATORS : Use for comparing value of two number and return the True or False
== : equals to used for comparing two values
!= : use for checking not equals to
< : less than
> : greater than
<= : less than or equal to
>= : greater than or equal to
'''
print(a==b)
print(a!=b)
print(a<b)
print(a>b)
print(a<=b)
print(a>=b)

'''
3. ASSIGNMENT OPERATORS is used for assigning value to a variable.
+= : adding and assigning
-= : sustracting and assigning
= : assigning to a value
*= : multiplying and assigning
etc
'''
a = 5
a += 5
print(a)

'''4. LOGICAL OPEARTORS is used to combine a conditional statement.
and : True if both cndition is true
or : True if one of the condition is true
not : inverts boolean value
'''
a = 5
b = 3
print(a>b and a==b)
print(a>b or a==b)
print(not a>b)

'''
5. Explain concept of type casting in python with examples .

ans. Type casting in python is a process in which one type of data assigned to a variable
is converted into another data type such as converting a string value into a integer
or integer into float etc
Conversion of data type is impotant because sometime we can't operate the value directly
and some functions or methodds requirre some special daata type input.
'''
#IMPLICIT TYPE CASTING :
#PYTHON automatically converts one data type to another without any explicit instructuion

a = 5     #integer value
b = 2.5    #float value
sum = a+b  #implicit converts the sum to float for the addition
print(sum) #outpu : 7.5 (float value)

#EXPLICIT TYPE CASTING
#Data types are manually converted one to another using python functions like
int(),float(), boolean(), list(), string(), tuples(),etc.

a = 5.7
b = int(a)  #converting data types from float vlue to int by truncating decimal part by using int.
print(b)

'''
How do conditional statement works in python? illustrate with an examples.

ans. Conditional statement in python are used to make decisions based on certain conditions
they check if the condition is True or Ffalse and execute code accordingnly .
The main conditional satement in pythons are :
'''
#1. IF: the if statement checks the condition in starting and if the condition is TRUE then
#the code under the syntax run properly.

age = int(input("enter your age"))
if age >=18:
    print("you are eligible to vote")

#ELSE: Else statement is used when the starting statement is incorrect, it act as fallback .

n = int(input("eneter a number"))
if n%2 == 0:
    print("number is even")
else:
        print("number is odd")

#ELIF : ELIF\else if is used to check multiple condition. If the first if condition is false then second second statement is checked
# and the process goes through the same way .

n = int(input("enter a number"))
if n>0:
    print("number is positive")
elif n<0:
    print("number is negative")
else:
    print("number is zero")

'''
7. Describe the different types of loops in python and their use case with examples .

ans. loops in python is to itirate \repeat the block of code untill the condition is met, the condition become false or it is terminated by user.
there are two types of loop in python are :
1. WHILE LOOP:
WHILE LOOP in python iterates the block of code untill the condition is true and when the condition is false.
or the user give command command to terminate the loop , or it will run to an infinite loop.

use case of while loop: while loops iterates the code untill the condition is true.
'''

count = 0
while count < 5:
    print(count)
    count += 1

#FOR LOOP :
#FOR LOOP in python is used iterate a block of code over sequence , goes one by one by sequence untill it fullfil the criteria.

#use case of for loop : Loop cases is used in python when an user have to go through each data in a collection and perform action on the that data .

j = int(input("enter a number"))
for i in range(1,11):
  print(j,"*",i,"=",j*i)
  print()